spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
          - id: auth-service
            uri: http://localhost:9000
            predicates:
              - Path=/api/auth/**
          - id: product-images
            uri: http://localhost:9001
            predicates:
              - Path=/api/images/**
          - id: product-service
            uri: http://localhost:9001
            predicates:
              - Path=/api/products/**
          - id: order-service
            uri: http://localhost:9002
            predicates:
              - Path=/api/orders/**
          - id: cart-service
            uri: http://localhost:9002
            predicates:
              - Path=/api/cart/**

server:
  port: 8080

# Auth Service Configuration
auth:
  service:
    url: http://localhost:9000
    validate:
      endpoint: /api/auth/validate

# JWT Configuration
jwt:
  secret: micromartsecretkeyforsecuringjwttokensintheecommerceapplication

# Public Endpoints (No Authentication Required)
public:
  endpoints: /api/auth/login,/api/auth/register,/api/auth/refresh,/api/auth/logout,/api/auth/verify-email,/api/products/**,/api/images/**,/api/orders/**,/api/cart/**